#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

if [ -z "$TMUX" ]; then
  tmux attach -t default || tmux new -s default
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# vim key 
bindkey -v
export KEYTIMEOUT=10
bindkey -M viins 'kj' vi-cmd-mode 
bindkey '^r' history-incremental-search-backward

# default editor
export VISUAL=vim
export LSCOLORS="exfxcxdxbxegedabagacad"
export API_PATH=/home/emeric/App/forks/ws-v2
export WEB_PATH=/home/emeric/App/forks/guesttoguest
export GRAPHQL_PATH=/home/emeric/App/forks/gtg-graphql
export HOST_USER=`whoami`
export HOST_IP="172.22.0.1"
export AWS_ACCESS_KEY_ID="AKIAI247NCHJITYPPYDQ"
export AWS_SECRET_ACCESS_KEY="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"

# alias
alias ll="ls -la"
alias la="ls -A"

