#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Customize to your needs...
# vim key 
bindkey -v

# default editor
export VISUAL=vim
export LSCOLORS="exfxcxdxbxegedabagacad"

# alias
alias ll="ls -la"
alias la="ls -A"

if [ -z "$TMUX" ]; then
  tmux attach -t default || tmux new -s default
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
